name: Lint and Test

on:
  push: # Запуск при каждом пуше в любую ветку
    branches:
      - '**' # Включает все ветки
  pull_request: # Запуск при создании pull request

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18] # Тестирование на нескольких версиях Node.js

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test
