name: Lint and Test

on:
  push:
    branches:
      - '**'
    # paths:
    #   - 'tailTalksApp/**' 
  pull_request:
    branches:
      - '**'
    # paths:
    #   - 'tailTalksApp/**' 

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Change directory to tailTalksApp
      run: cd tailTalksApp

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd tailTalksApp
        npm ci

    - name: Run linter
      run: |
        cd tailTalksApp
        npm run lint

    - name: Run tests
      run: |
        cd tailTalksApp
        npm run test
